In [2]:
import numpy as np

In [3]:
arr = np.arange(50).reshape((10,5))

In [4]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [5]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [6]:
np.dot(arr.T, arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [8]:
arr3d = np.arange(50)

In [10]:
arr3d.reshape(,7.,2)

ValueError: total size of new array must be unchanged

In [25]:
arr3d.T #transpose.(2,1,0), normal = (0,1,2)

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

In [46]:
arr3d.transpose((1,2,0))

array([[[ 0, 10, 20, 30, 40],
        [ 1, 11, 21, 31, 41]],

       [[ 2, 12, 22, 32, 42],
        [ 3, 13, 23, 33, 43]],

       [[ 4, 14, 24, 34, 44],
        [ 5, 15, 25, 35, 45]],

       [[ 6, 16, 26, 36, 46],
        [ 7, 17, 27, 37, 47]],

       [[ 8, 18, 28, 38, 48],
        [ 9, 19, 29, 39, 49]]])

In [44]:
arr3d.transpose((0,2,1))

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]],

       [[20, 22, 24, 26, 28],
        [21, 23, 25, 27, 29]],

       [[30, 32, 34, 36, 38],
        [31, 33, 35, 37, 39]],

       [[40, 42, 44, 46, 48],
        [41, 43, 45, 47, 49]]])

In [34]:
arr = np.array([[1,2,3]])

In [36]:
arr

array([[1, 2, 3]])

In [53]:
arr.swapaxes(1,0)

array([[1],
       [2],
       [3]])