In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1, arr1], axis = 1) #axis = 1 is 'y'.

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
np.concatenate([arr1, arr1], axis = 0) #axis = 0 is 'x'

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ser1 = Series([0,1,2], index=['T', 'U', 'V'])
ser2 = Series([3,4], index = ['X', 'Y'])

ser1

T    0
U    1
V    2
dtype: int64

In [11]:
ser2

X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [36]:
pd.concat([ser1,ser2], axis = 1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [37]:
pd.concat([ser1, ser2], keys = ['cat1', 'cat2'], axis  = 1)

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [31]:
dframe1 = DataFrame(np.random.randn(12).reshape(4,3), columns = ['X', 'Y', 'Z']) #randn(4,3)'de olur
dframe2 = DataFrame(np.random.randn(3,3), columns = ['Y', 'Q', 'X'])

In [32]:
dframe1

X         Y         Z
0  0.959321 -0.482556  0.097477
1 -0.463788  0.725237  1.727928
2 -0.396741  1.775483 -0.608881
3 -0.096013 -0.023663 -0.598754

In [23]:
dframe2

Y         Q         X
0  0.185527 -1.238526 -2.006546
1 -0.178532  0.890504  0.441795
2 -0.619787  0.291514 -0.765488

In [33]:
pd.concat([dframe1, dframe2]) #0-1-2-3 from one matrix, 0-1-2 from another matrix

Q         X         Y         Z
0       NaN  0.959321 -0.482556  0.097477
1       NaN -0.463788  0.725237  1.727928
2       NaN -0.396741  1.775483 -0.608881
3       NaN -0.096013 -0.023663 -0.598754
0 -0.596992 -0.639722  0.079086       NaN
1  0.856496 -0.299731  1.624386       NaN
2 -0.175950 -1.102719  0.250546       NaN

In [34]:
pd.concat([dframe1,dframe2], ignore_index = True) #ignore passed indexes.

Q         X         Y         Z
0       NaN  0.959321 -0.482556  0.097477
1       NaN -0.463788  0.725237  1.727928
2       NaN -0.396741  1.775483 -0.608881
3       NaN -0.096013 -0.023663 -0.598754
4 -0.596992 -0.639722  0.079086       NaN
5  0.856496 -0.299731  1.624386       NaN
6 -0.175950 -1.102719  0.250546       NaN