In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr) #e^number_at_index

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
A = np.random.randn(10) #normal distribution values of some numbers

In [9]:
A

array([ 1.95671551, -0.37995949,  0.25715895,  0.4424378 , -1.21246444,
        2.36926064, -0.31125609, -0.18115951,  1.31119385, -0.29889044])

In [11]:
B = np.random.randn(10)
B

array([ 1.3224059 ,  0.36335403,  0.96036573,  0.29470113, -0.77436549,
        1.09925757,  0.28633582, -0.21687825, -0.8147794 , -1.61256191])

In [12]:
# Binary Functions

In [13]:
np.add(A,B)

array([ 3.27912141, -0.01660546,  1.21752468,  0.73713893, -1.98682993,
        3.46851821, -0.02492026, -0.39803776,  0.49641444, -1.91145235])

In [16]:
np.maximum(A,B)

array([ 1.95671551,  0.36335403,  0.96036573,  0.4424378 , -0.77436549,
        2.36926064,  0.28633582, -0.18115951,  1.31119385, -0.29889044])